/* Integrated prefixed-route browser QA. Uses Playwright; browser/server share one process.
   PORTAL_CHROMIUM=/path/to/chromium NODE_PATH=/path/to/node_modules node tests/portal-browser.cjs --tools-only
   Run without --tools-only after the portal is complete. */
'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
let chromium;try{({chromium}=require('playwright-core'));}catch{({chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright-core'));}
const root=path.resolve(__dirname,'..'),out=path.join(__dirname,'artifacts'),prefix='/SmartAction/';fs.mkdirSync(out,{recursive:true});
const candidates=[process.env.PORTAL_CHROMIUM,'/workspace/scratch/a8695db12b98/qa/bin/chromium','/usr/bin/chromium',chromium.executablePath()];
const executablePath=candidates.find(p=>p&&fs.existsSync(p)&&fs.statSync(p).size>1000000);if(!executablePath)throw Error('Set PORTAL_CHROMIUM to a working Chromium binary.');
const types={'.html':'text/html;charset=utf-8','.js':'text/javascript;charset=utf-8','.mjs':'text/javascript;charset=utf-8','.json':'application/json','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.woff2':'font/woff2','.wasm':'application/wasm','.bin':'application/octet-stream','.txt':'text/plain;charset=utf-8','.webm':'video/webm','.mp4':'video/mp4'};
const missing=[];
const server=http.createServer((req,res)=>{let url;try{url=new URL(req.url,'http://qa.invalid');}catch{res.writeHead(400);return res.end();}if(url.pathname==='/favicon.ico'){res.writeHead(204);return res.end();}if(!url.pathname.startsWith(prefix)){res.writeHead(404);return res.end('Outside project');}let file=path.resolve(root,decodeURIComponent(url.pathname.slice(prefix.length)));if(!file.startsWith(root+path.sep)&&file!==root){res.writeHead(403);return res.end();}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!fs.existsSync(file)){missing.push(url.pathname);res.writeHead(404);return res.end('Missing');}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(res);});
const results=[],errors=[];let browser,base;
const test=async(name,fn)=>{try{const detail=await fn();results.push({name,ok:true,detail:detail??null});console.log('PASS '+name);}catch(e){results.push({name,ok:false,error:e.stack||String(e)});console.log('FAIL '+name+' '+e.message);}};
const waitDownload=async(page,trigger)=>{const [download]=await Promise.all([page.waitForEvent('download',{timeout:20000}),trigger()]);const file=path.join(out,download.suggestedFilename());await download.saveAs(file);assert(fs.statSync(file).size>0);return {download,file,size:fs.statSync(file).size};};
function track(page){page.on('pageerror',e=>errors.push({page:page.url(),message:e.message}));}
async function runTools(context){
 const page=await context.newPage();track(page);await page.goto(base+'tools/?lang=en');await page.waitForSelector('#paintCanvas');
 await test('Tools: prefixed route and canvas input',async()=>{const box=await page.locator('#paintCanvas').boundingBox();await page.mouse.move(box.x+box.width*.3,box.y+box.height*.4);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.7,{steps:12});await page.mouse.up();assert.equal(await page.locator('#paintCanvas').evaluate(c=>c.width),1280);});
 await test('Tools: actual PNG download',async()=>{const r=await waitDownload(page,()=>page.click('#paintExport'));assert.equal(fs.readFileSync(r.file).subarray(1,4).toString(),'PNG');return {bytes:r.size};});
 await test('Tools: standalone HTML slide export omits private notes',async()=>{await page.click('[data-tool="slides"]');await page.fill('#slideTitleInput','Portal QA <script>test</script>');await page.fill('#slideBodyInput','Prefixed deployment test\n第二行');await page.fill('#slideNotesInput','PRIVATE_NOTES_QA_20261009');const r=await waitDownload(page,()=>page.click('#slidesHTML'));const h=fs.readFileSync(r.file,'utf8');assert(!h.includes('PRIVATE_NOTES_QA_20261009'));assert(h.includes('&lt;script&gt;'));return {bytes:r.size};});
 await test('Tools: actual local text download and arithmetic',async()=>{await page.click('[data-tool="notes"]');await page.fill('#noteBody','SmartAction 本機工具測試');const r=await waitDownload(page,()=>page.click('#noteText'));assert(fs.readFileSync(r.file,'utf8').includes('本機工具測試'));await page.fill('#calcA','12');await page.fill('#calcB','3');await page.selectOption('#calcOp','multiply');await page.click('#calculate');assert.equal((await page.locator('#calcResult').textContent()).trim(),'36');});
 await test('Tools: short video is actually encoded and downloaded',async()=>{await page.click('[data-tool="video"]');const data=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=320;c.height=180;const x=c.getContext('2d'),stream=c.captureStream(15),r=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp8')?'video/webm;codecs=vp8':'video/webm'}),chunks=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};const ended=new Promise(resolve=>r.onstop=resolve);let i=0;const draw=()=>{x.fillStyle='#183d35';x.fillRect(0,0,320,180);x.fillStyle='#efb66d';x.fillRect((i++*6)%280,65,40,40);};draw();r.start(100);const id=setInterval(draw,60);await new Promise(resolve=>setTimeout(resolve,2300));clearInterval(id);r.stop();await ended;stream.getTracks().forEach(t=>t.stop());const b=new Blob(chunks,{type:'video/webm'});return Array.from(new Uint8Array(await b.arrayBuffer()));});await page.locator('#videoFile').setInputFiles({name:'qa-source.webm',mimeType:'video/webm',buffer:Buffer.from(data)});await page.waitForFunction(()=>{const v=document.querySelector('#videoPreview');return Number.isFinite(v.duration)&&v.duration>1;},{},{timeout:12000});await page.fill('#videoStart','0.2');await page.fill('#videoEnd','1.6');await page.uncheck('#videoAudio');const r=await waitDownload(page,()=>page.click('#videoExport'));assert(r.size>400);return {sourceBytes:data.length,outputBytes:r.size,filename:path.basename(r.file)};});
 await page.close();
}
async function runAssistant(context){const page=await context.newPage();track(page);const modelRequests=[];page.on('request',r=>{if(/\/models\/|onnx|\.wasm/.test(r.url()))modelRequests.push(r.url());});await page.goto(base+'assistant/?lang=en');await test('Assistant: source lookup under prefix without auto-loading model',async()=>{await page.fill('#prompt','silicon photonics');await page.click('#search');await page.waitForFunction(()=>document.querySelector('#results').textContent.trim().length>30);assert(await page.locator('#results a').count()>0);assert(await page.locator('#generate').isDisabled());assert.equal(modelRequests.length,0);});await page.close();}
async function runMarket(context){const page=await context.newPage();track(page);await page.goto(base+'market/?lang=en');await page.waitForSelector('#products button');await test('Market: local CSV analysis on prefixed route',async()=>{await page.locator('#csv-file').setInputFiles({name:'prices.csv',mimeType:'text/csv',buffer:Buffer.from('date,close\n2026-10-01,100\n2026-10-02,110\n2026-10-03,99\n')});await page.click('#analyze');await page.waitForFunction(()=>document.querySelector('#metrics').textContent.trim().length>10);assert((await page.locator('#metrics').textContent()).includes('-1'));assert(await page.locator('#chart').isVisible());});await test('Market: wishlist is local and exportable',async()=>{await page.locator('#products button').first().click();await page.locator('summary').first().click();const r=await waitDownload(page,()=>page.click('#export-wishlist'));assert(r.size>30);});await page.close();}
async function runQuiz(context){
 const page=await context.newPage();track(page);
 await test('Question bank: 100 prerendered entries with concealed sources and quiz links',async()=>{for(const name of ['question-bank.html','en/question-bank.html']){await page.goto(base+name);assert.equal(await page.locator('article.reading-card').count(),100);assert.equal(await page.locator('details[open]').count(),0);await page.locator('#Q001 summary').click();assert(await page.locator('#Q001 details a').first().isVisible());const href=await page.locator('#Q066 a[href*="quiz.html"]').getAttribute('href');assert(href.includes('quiz.html')&&href.includes('Q066'));}});
 await page.goto(base+'quiz.html?lang=en&q=Q001');await page.waitForSelector('#answer-form');
 await test('Quiz: 100 questions with hidden source and standard answer',async()=>{assert.equal(await page.evaluate(()=>SA_QUESTIONS.length),100);assert(!(await page.locator('#hint-panel').isVisible()));assert.equal(await page.locator('#question-sources a').count(),0);assert(await page.locator('#reveal-answer').isDisabled());assert(!(await page.locator('#answer-detail').isVisible()));});
 await test('Quiz: reveal exact source only on hint action',async()=>{await page.click('#toggle-hint');assert(await page.locator('#hint-panel').isVisible());assert(await page.locator('#question-sources a').count()>0);assert((await page.locator('#question-sources a').first().getAttribute('href')).startsWith('https://www.who.int/'));});
 await test('Quiz: attempted wrong answer then standard answer reveal',async()=>{await page.locator('input[name="answer"][value="0"]').check();await page.click('#check-answer');assert(!(await page.locator('#reveal-answer').isDisabled()));await page.click('#reveal-answer');assert(await page.locator('#answer-detail').isVisible());assert((await page.locator('#answer-detail').textContent()).includes('brain'));});
 await test('Quiz: correct answer saved between reloads',async()=>{await page.locator('input[name="answer"][value="1"]').check();await page.click('#check-answer');assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('smartaction.quiz.v1')).progress.Q001.everCorrect));await page.reload();await page.waitForSelector('#answer-form');assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('smartaction.quiz.v1')).progress.Q001.everCorrect));});
 await test('Quiz: NFKC and case-normalized fill answer',async()=>{await page.goto(base+'quiz.html?lang=en&q=Q066');await page.waitForSelector('#fill-answer');await page.fill('#fill-answer','  ＤＯＰＡＭＩＮＥ  ');await page.click('#check-answer');assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('smartaction.quiz.v1')).progress.Q066.lastCorrect));assert((await page.locator('#feedback').textContent()).toLowerCase().includes('correct'));});
 await page.screenshot({path:path.join(out,'quiz-desktop.png'),fullPage:false});await page.close();
 const phone=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,locale:'zh-TW'});const mp=await phone.newPage();track(mp);await test('Quiz: mobile touch layout and complete fill input',async()=>{await mp.goto(base+'quiz.html?lang=zh-TW&q=Q066');await mp.waitForSelector('#fill-answer');const overflow=await mp.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert(overflow<=2,'overflow='+overflow);await mp.fill('#fill-answer','多巴胺');await mp.click('#check-answer');assert(await mp.evaluate(()=>JSON.parse(localStorage.getItem('smartaction.quiz.v1')).progress.Q066.lastCorrect));await mp.screenshot({path:path.join(out,'quiz-mobile.png'),fullPage:true});});await phone.close();
}
async function runResources(context){
 const page=await context.newPage();track(page);await page.goto(base+'resources.html?lang=en');await page.waitForSelector('#resource-list .resource-card');
 await test('Resources: 68 resources, region filtering and clear empty state',async()=>{assert.equal(await page.locator('#resource-list .resource-card').count(),68);await page.selectOption('#resource-region','高雄／台灣');const local=await page.locator('#resource-list .resource-card').count();assert(local>0&&local<68);await page.fill('#resource-search','ZZZ_DOES_NOT_EXIST_QA');assert.equal(await page.locator('#resource-list .resource-card').count(),0);assert(await page.locator('#resource-empty').isVisible());await page.fill('#resource-search','');await page.selectOption('#resource-region','');assert.equal(await page.locator('#resource-list .resource-card').count(),68);});
 await test('Resources: live language switching retains search functionality',async()=>{await page.selectOption('#language-select','zh-CN');await page.waitForFunction(()=>document.documentElement.lang==='zh-CN');await page.fill('#resource-search','长庚');assert(await page.locator('#resource-list .resource-card').count()>0);assert((await page.locator('#resource-list').textContent()).includes('长庚'));});
 await test('Knowledge: eight source-linked guides and working anchor navigation',async()=>{await page.goto(base+'knowledge.html?lang=en#nutrition');await page.waitForSelector('#knowledge-content .reading-card');assert.equal(await page.locator('#knowledge-content .reading-card').count(),8);assert(await page.locator('#nutrition .source-links a').count()>0);assert((await page.locator('#nutrition').textContent()).toLowerCase().includes('protein'));assert.equal(await page.locator('#knowledge-nav a').count(),8);});
 await page.close();
 const phone=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,locale:'ar'});const mp=await phone.newPage();track(mp);
 await test('Resources and knowledge: mobile Arabic interface without overflow',async()=>{for(const name of ['resources.html','knowledge.html']){await mp.goto(base+name+'?lang=ar');await mp.waitForFunction(()=>document.documentElement.lang==='ar');assert.equal(await mp.locator('html').getAttribute('dir'),'rtl');assert((await mp.evaluate(()=>document.documentElement.scrollWidth-innerWidth))<=2,name);}});await phone.close();
}
async function runPortal(context){
 const page=await context.newPage();track(page);await page.goto(base+'?lang=zh-TW');await page.waitForSelector('#home-articles .article-row-new');
 await test('Portal: no horizontal desktop overflow',async()=>{const n=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert(n<=2,'overflow='+n);return {width:await page.evaluate(()=>innerWidth)};});
 await test('Portal: five compact icon folders',async()=>{const hrefs=await page.locator('.folder-strip a').evaluateAll(a=>a.map(x=>x.getAttribute('href')));for(const x of ['market/','tools/','play/','assistant/','quiz.html'])assert(hrefs.some(h=>h&&h.includes(x)),x);assert.equal(await page.locator('.folder-strip svg').count(),5);const h=await page.locator('.folder-strip').evaluate(el=>el.getBoundingClientRect().height);assert(h<230,'desktop folder height='+h);return {height:h};});
 await test('Portal: more articles remain single rows with icons, 6 to 48',async()=>{assert.equal(await page.locator('#home-articles .article-row-new').count(),6);await page.click('#more-articles');assert.equal(await page.locator('#home-articles .article-row-new').count(),14);while(await page.locator('#more-articles').isVisible())await page.click('#more-articles');assert.equal(await page.locator('#home-articles .article-row-new').count(),48);assert.equal(await page.locator('#home-articles img').count(),48);const bounds=await page.locator('#home-articles .article-row-new').evaluateAll(a=>a.map(x=>{const b=x.getBoundingClientRect();return {x:b.x,y:b.y,bottom:b.bottom};}));assert(bounds.slice(1).every((x,i)=>x.y>=bounds[i].bottom-1&&Math.abs(x.x-bounds[i].x)<2));});
 const langs=await page.evaluate(()=>SA_HUB_I18N.languages.map(x=>x.code));
 for(const lang of langs)await test('Portal: actual language navigation '+lang,async()=>{await page.selectOption('#language-select',lang);await page.waitForURL(u=>u.searchParams.get('lang')===lang);await page.waitForFunction(l=>window.SAHub?.lang===l,lang);assert.equal(await page.locator('html').getAttribute('lang'),lang);assert.equal((await page.locator('h1').textContent()).trim(),await page.evaluate(l=>SA_HUB_I18N.messages[l].tagline,lang));assert.equal(await page.locator('html').getAttribute('dir'),lang==='ar'?'rtl':'ltr');assert((await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth))<=2);});
 await page.goto(base+'?lang=zh-TW');await page.waitForSelector('#home-articles .article-row-new');await page.screenshot({path:path.join(out,'portal-desktop.png'),fullPage:false});
 await test('Portal: manual language survives refresh',async()=>{await page.selectOption('#language-select','ja');await page.waitForURL(u=>u.searchParams.get('lang')==='ja');await page.reload();await page.waitForFunction(()=>SAHub.lang==='ja');assert.equal(await page.locator('#language-select').inputValue(),'ja');});
 await test('Videos: 14 user-controlled players; no initial embeds',async()=>{await page.goto(base+'videos.html?lang=en');await page.waitForSelector('.video-card');assert.equal(await page.locator('.video-card').count(),14);assert.equal(await page.locator('iframe').count(),0);await page.locator('.video-poster button').first().click();assert.equal(await page.locator('iframe').count(),1);assert((await page.locator('iframe').getAttribute('src')).startsWith('https://www.youtube-nocookie.com/embed/'));});
 await page.close();
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true,locale:'zh-TW'});const mp=await mobile.newPage();track(mp);
 for(const lang of ['zh-TW','en','ar'])await test('Mobile: home 390px layout '+lang,async()=>{await mp.goto(base+'?lang='+lang);await mp.waitForSelector('.folder-strip a');const overflow=await mp.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert(overflow<=2,'overflow='+overflow);assert.equal(await mp.locator('.folder-strip a').count(),5);if(lang==='zh-TW')await mp.screenshot({path:path.join(out,'portal-mobile.png'),fullPage:true});return {overflow};});
 await mobile.close();
 const file=await context.newPage();track(file);await test('Videos: file opening offers direct YouTube fallback',async()=>{await file.goto('file://'+path.join(root,'videos.html')+'?lang=en');await file.waitForSelector('.video-card');await file.locator('.video-poster button').first().click();assert.equal(await file.locator('iframe').count(),0);assert((await file.locator('.video-poster').first().textContent()).includes('local HTTP'));});await file.close();
}
(async()=>{try{await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}${prefix}`;browser=await chromium.launch({executablePath,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--autoplay-policy=no-user-gesture-required']});const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'en-US',acceptDownloads:true});await context.route('**/*',route=>{const u=new URL(route.request().url());if(['data:','blob:','file:'].includes(u.protocol)||u.hostname==='127.0.0.1')return route.continue();return route.abort();});if(!process.argv.includes('--modules-only')&&!process.argv.includes('--portal-only'))await runTools(context);if(!process.argv.includes('--tools-only')){if(!process.argv.includes('--portal-only')){await runMarket(context);await runAssistant(context);}if(!process.argv.includes('--modules-only')){await runPortal(context);await runResources(context);if(fs.existsSync(path.join(root,'quiz.html')))await runQuiz(context);}}
 await test('No JavaScript page errors',async()=>assert.deepEqual(errors,[]));await test('No missing local requests',async()=>assert.deepEqual([...new Set(missing)],[]));await context.close();
 }catch(e){results.push({name:'suite setup',ok:false,error:e.stack||String(e)});}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));const report={date:new Date().toISOString(),mode:process.argv.slice(2),base,executablePath,passed:results.filter(x=>x.ok).length,total:results.length,results,errors,missing};fs.writeFileSync(path.join(out,'portal-browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,total:report.total},null,2));process.exitCode=results.some(x=>!x.ok)?1:0;}})();
