import {test} from 'node:test';import assert from 'node:assert/strict';import {MarketHub} from '../../backend/market-worker/src/worker.js';
function state(){const map=new Map();return {storage:{get:async k=>structuredClone(map.get(k)),put:async(k,v)=>map.set(k,structuredClone(v)),delete:async k=>map.delete(k)},map};}
const req=(s,p='twse',kind='quote')=>new Request('https://internal/'+kind+'?provider='+p+'&symbol='+s);
test('Concurrent TWSE queries share a single fetch and retain true EOD metadata',async()=>{const old=global.fetch;let calls=0;global.fetch=async()=>{calls++;return Response.json([{Date:'1151007',Code:'2330',Name:'test record',ClosingPrice:'100',OpeningPrice:'99',HighestPrice:'101',LowestPrice:'98',TradeVolume:'123'}]);};try{const hub=new MarketHub(state(),{});const rs=await Promise.all(Array.from({length:20},()=>hub.fetch(req('2330'))));const q=await rs[0].json();assert.equal(calls,1);assert.equal(q.freshness,'eod');assert.equal(q.asOf,'2026-10-07 (Asia/Taipei)');assert.equal(q.price,100);assert.ok(q.fetchedAt);}finally{global.fetch=old;}});
test('TWSE large datasets are chunked below per-value limits',async()=>{const old=global.fetch;global.fetch=async()=>Response.json(Array.from({length:1500},(_,i)=>({Date:'1151007',Code:String(1000+i),Name:'fixture'.repeat(12),ClosingPrice:'100'})));try{const ctx=state(),hub=new MarketHub(ctx,{});assert.equal((await hub.fetch(req('2330'))).status,200);for(const v of ctx.map.values())assert.ok(Buffer.byteLength(JSON.stringify(v))<128*1024);}finally{global.fetch=old;}});
test('Missing provider key is explicit and secrets never returned',async()=>{const hub=new MarketHub(state(),{});const r=await hub.fetch(req('IBM','alpha'));assert.equal(r.status,503);assert.match((await r.json()).error,/key is not configured/);});
test('Unsupported global symbols rejected before quota consumed',async()=>{const ctx=state(),hub=new MarketHub(ctx,{});assert.equal((await hub.fetch(req('UNLISTED','alpha'))).status,403);assert.equal(ctx.map.size,0);});
test('Source failure stays an error rather than invented stale data',async()=>{const old=global.fetch;global.fetch=async()=>new Response('unavailable',{status:503});try{const r=await new MarketHub(state(),{}).fetch(req('2330'));assert.equal(r.status,502);assert.equal((await r.json()).price,undefined);}finally{global.fetch=old;}});
test('Global upstream daily quota is enforced',async()=>{const ctx=state(),hub=new MarketHub(ctx,{ALPHA_DAILY_LIMIT:'1'});await hub.reserve('alpha');await assert.rejects(()=>hub.reserve('alpha'),e=>e.status===429);});
