/* Optional developer smoke test; needs Playwright + Chromium, neither needed by visitors. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core');
const fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/workspace/scratch/a8695db12b98/qa/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--autoplay-policy=no-user-gesture-required']});
 const context=await browser.newContext({viewport:{width:1440,height:1100},locale:'en-US',acceptDownloads:true});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const check=(name,condition)=>{assert(condition,name);console.log('PASS '+name);};
 await page.goto('file://'+path.join(__dirname,'index.html'));
 check('English automatic language',await page.locator('h1').textContent()==='Turn an idea into a creation.');
 const pbox=await page.locator('#paintCanvas').boundingBox();
 await page.mouse.move(pbox.x+100,pbox.y+100);await page.mouse.down();await page.mouse.move(pbox.x+180,pbox.y+180,{steps:15});await page.mouse.up();
 check('Paint changes actual pixels',await page.evaluate(()=>{const c=document.getElementById('paintCanvas'),d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let n=0;for(let i=0;i<d.length;i+=4)if(d[i]<150)n++;return n>200;}));
 await page.click('#paintUndo');check('Paint undo restores white canvas',await page.evaluate(()=>document.getElementById('paintCanvas').getContext('2d').getImageData(110,110,1,1).data[0]===255));
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=320;c.height=180;const x=c.getContext('2d');x.fillStyle='rgb(200,30,10)';x.fillRect(0,0,320,180);return c.toDataURL().split(',')[1];});
 await page.click('[data-tool=image]');await page.setInputFiles('#imageFile',{name:'test.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.waitForFunction(()=>document.getElementById('imageCanvas').width===320&&!document.getElementById('imageCanvas').hidden);
 await page.check('#grayscale');await page.waitForTimeout(80);check('Grayscale changes actual pixels',await page.evaluate(()=>{const p=document.getElementById('imageCanvas').getContext('2d').getImageData(50,50,1,1).data;return p[0]===p[1]&&p[1]===p[2];}));
 await page.click('#imageRotate');check('Rotate swaps dimensions',await page.evaluate(()=>document.getElementById('imageCanvas').width===180&&document.getElementById('imageCanvas').height===320));
 await page.fill('#cropX','10');await page.fill('#cropY','20');await page.fill('#cropW','100');await page.fill('#cropH','150');await page.click('#cropApply');check('Keyboard crop uses selected pixels',await page.evaluate(()=>document.getElementById('imageCanvas').width===100&&document.getElementById('imageCanvas').height===150));
 await page.fill('#resizeW','200');await page.click('#imageResize');check('Resize keeps aspect ratio',await page.evaluate(()=>document.getElementById('imageCanvas').width===200&&document.getElementById('imageCanvas').height===300));
 const imageDl=page.waitForEvent('download');await page.click('#imagePNG');check('PNG download has correct extension',(await imageDl).suggestedFilename().endsWith('.png'));
 await page.click('[data-tool=slides]');await page.fill('#slideTitleInput','<img src=x onerror=alert(1)>');await page.fill('#slideBodyInput','Line one\nLine two');await page.click('#slideAdd');await page.fill('#slideTitleInput','Second slide');await page.click('#slideUp');check('Slide reorder works',await page.locator('#slideList button').first().textContent()==='1. Second slide');
 await page.fill('#slideNotesInput','PRIVATE NOTES 314159');const htmlDl=page.waitForEvent('download');await page.click('#slidesHTML');const dl=await htmlDl;const html=fs.readFileSync(await dl.path(),'utf8');check('HTML presentation escapes user content and omits notes',html.includes('&lt;img')&&!html.includes('PRIVATE NOTES 314159'));
 await page.click('#present');check('Presentation modal opens',await page.locator('#presentation').isVisible());await page.click('#presentNext');check('Presentation advances',await page.locator('#presentCount').textContent()==='2 / 2');await page.click('#presentClose');
 const invalid=JSON.stringify({format:'smartaction-slides',version:1,slides:[{title:'oops',body:'x',bg:'red;" onmouseover="evil()'}]});await page.setInputFiles('#slidesFile',{name:'bad.json',mimeType:'application/json',buffer:Buffer.from(invalid)});await page.waitForFunction(()=>document.getElementById('notice').textContent.startsWith('Import failed'));check('Malformed project rejected',(await page.locator('#notice').textContent()).startsWith('Import failed'));
 await page.click('[data-tool=notes]');await page.fill('#calcA','12');await page.fill('#calcB','0');await page.selectOption('#calcOp','divide');await page.click('#calculate');check('Division by zero handled',(await page.locator('#calcResult').textContent()).includes('zero'));
 await page.fill('#noteBody','Hello 聰動');check('Note character counter updates',(await page.locator('#noteCount').textContent()).includes('8'));
 const fixture=process.env.VIDEO_FIXTURE;if(fixture){await page.click('[data-tool=video]');await page.setInputFiles('#videoFile',fixture);await page.waitForFunction(()=>document.getElementById('videoPreview').readyState>=2);await page.fill('#videoStart','0.5');await page.fill('#videoEnd','2.5');await page.uncheck('#videoAudio');const vd=page.waitForEvent('download',{timeout:30000});await page.click('#videoExport');const result=await vd;const resultPath=path.join(__dirname,'qa-trim.'+(result.suggestedFilename().endsWith('mp4')?'mp4':'webm'));await result.saveAs(resultPath);check('Video re-encoding produces real file',fs.statSync(resultPath).size>1000);await page.click('#videoExport');await page.waitForTimeout(100);await page.click('#videoCancel');await page.waitForTimeout(100);check('Video cancellation restores controls',!await page.locator('#videoExport').isDisabled());}
 await page.selectOption('#language','zh-Hant');check('Traditional Chinese language switches',await page.locator('h1').textContent()==='把想法，變成作品。');
 await page.setViewportSize({width:390,height:844});await page.click('[data-tool=slides]');check('Mobile layout has no page overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2));await page.screenshot({path:path.join(__dirname,'qa-mobile.png'),fullPage:true});
 await page.setViewportSize({width:1440,height:1100});await page.selectOption('#language','en');await page.click('[data-tool=paint]');await page.screenshot({path:path.join(__dirname,'qa-desktop.png'),fullPage:true});
 check('No uncaught browser errors',errors.length===0);await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
